### ISSUE TITLE
8.x-php8.0 fails to login to Pantheon

### ISSUE THREAD

**Issue by CdrMarks** [pantheon-systems/docker-build-tools-ci#88]
See https://app.circleci.com/pipelines/github/pantheon-systems/pantheon_advanced_page_cache/639/workflows/261bdd07-5d61-4b49-9ec5-8f8e3e86001c/jobs/1906

```
#!/bin/bash -eo pipefail
terminus auth:login -n --machine-token="$TERMINUS_TOKEN"
 [notice] Logging in via machine token.
 [notice] Found a machine token for steve.p*********@pantheon.io.
 [error]  No user ID. Please login via terminus auth:login 

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by davereid-pfg** [comment]
Looksl ike this is fixed with https://github.com/pantheon-systems/pantheon_advanced_page_cache/pull/33

**Comment by CdrMarks** [comment]
Steve and I ended up going with `quay.io/pantheon-public/build-tools-ci:7.x`.  

This bug still occurs when using the 8.x-php8.0 image.
See: https://github.com/pantheon-systems/pantheon_advanced_page_cache/commit/f2f7e54355187ea449610af34125acb4b2c0a39b
